### ISSUE TITLE
TLS error when running client.py and server.py

### ISSUE THREAD

**Issue by xiasuper** [Synss/python-mbedtls#110]
Traceback (most recent call last):
  File "D:\codes\DTLSpypy\python-mbedtls\programs\server.py", line 207, in <module>
    main(parse_args())
  File "D:\codes\DTLSpypy\python-mbedtls\programs\server.py", line 199, in main
    srv.run(partial(echo_handler, packet_size=4069))
  File "D:\codes\DTLSpypy\python-mbedtls\programs\server.py", line 121, in run
    self._run(conn_handler)
  File "D:\codes\DTLSpypy\python-mbedtls\programs\server.py", line 125, in _run
    with self._make_connection(self._sock) as conn:
  File "D:\codes\DTLSpypy\python-mbedtls\programs\server.py", line 52, in _make_dtls_connection
    conn.do_handshake()
  File "D:\codes\DTLSpypy\py39\lib\site-packages\mbedtls\tls.py", line 441, in do_handshake
    self._buffer.do_handshake()
  File "src\\mbedtls\\_tls.pyx", line 1147, in mbedtls._tls.MbedTLSBuffer.do_handshake
  File "src\\mbedtls\\_tls.pyx", line 1172, in mbedtls._tls.MbedTLSBuffer._handle_handshake_response
  File "src\\mbedtls\\exceptions.pyx", line 53, in mbedtls.exceptions.check_error
  File "src\\mbedtls\\exceptions.pyx", line 56, in mbedtls.exceptions.check_error
mbedtls.exceptions.TLSError: TLSError([0x6980] 'SSL - None of the common ciphersuites is usable (eg, no suitable certificate, see debug messages)')

**Comment by Synss** [comment]
There is a template for reporting bugs. I can’t help you with the information you’ve provided.

Regarding usage of the client and server programs, have a look at the examples in `test_tls.py`. The tests were flaky under windows in the CI, though. Since I don’t have a windows machine available, I wasn’t able to look further into it.

**Comment by Synss** [comment]
Closing because reporting an issue with only a stack trace isn’t serious.
