### ISSUE TITLE
server.py and client.py still have bugs when running on the Ubuntu system.

### ISSUE THREAD

**Issue by xiasuper** [Synss/python-mbedtls#112]
![Ubuntu-2024-05-21-15-55-42](https://github.com/Synss/python-mbedtls/assets/168046941/adf5ef8c-21ee-483b-aabd-719dbebb9e7b)

**NOTE: Please use stackoverflow for support questions**.
This repository's issues are reserved for feature requests and bug reports.

## I am submitting a …

  - [ x] bug report
  - [ ] feature request

## Description
ia@xia-virtual-machine:~/pythonDTLSS/python-mbedtls/programs$ python3 server.py --dtls
Traceback (most recent call last):
  File "/home/xia/pythonDTLSS/python-mbedtls/programs/server.py", line 207, in <module>
    main(parse_args())
  File "/home/xia/pythonDTLSS/python-mbedtls/programs/server.py", line 199, in main
    srv.run(partial(echo_handler, packet_size=4069))
  File "/home/xia/pythonDTLSS/python-mbedtls/programs/server.py", line 121, in run
    self._run(conn_handler)
  File "/home/xia/pythonDTLSS/python-mbedtls/programs/server.py", line 125, in _run
    with self._make_connection(self._sock) as conn:
  File "/home/xia/pythonDTLSS/python-mbedtls/programs/server.py", line 52, in _make_dtls_connection
    conn.do_handshake()
  File "/home/xia/.local/lib/python3.10/site-packages/mbedtls/tls.py", line 441, in do_handshake
    self._buffer.do_handshake()
  File "src/mbedtls/_tls.pyx", line 1147, in mbedtls._tls.MbedTLSBuffer.do_handshake
  File "src/mbedtls/_tls.pyx", line 1172, in mbedtls._tls.MbedTLSBuffer._handle_handshake_response
  File "src/mbedtls/exceptions.pyx", line 53, in mbedtls.exceptions.check_error
  File "src/mbedtls/exceptions.pyx", line 56, in mbedtls.exceptions.check_error
mbedtls.exceptions.TLSError: TLSError([0x6980] 'SSL - None of the common ciphersuites is usable (eg, no suitable certificate, see debug messages)')

### Steps to reproduce

1.
1.
1.

### Minimal demo of the problem

```python
>>> import mbedtls
...
```

**Comment by Synss** [comment]
Client and server communication is tested in the CI before publication so I am pretty sure that this works. You should really read through the tests as I told you in your previous issue.

This is not a support forum. I unfortunately have no time to offer such a service.

I also don’t have a computer at the moment.

**Comment by Synss** [comment]
Anyway, it looks like the error message is correct. You’re not passing any PSK so the handshake fails. That’s not a bug, is it?

Lastly, please don’t open identical issues. That’s not helping anyone.
